```{r init}
cat('\014')
rm(list=ls())
ec<-function(x) strsplit(x,',')[[1]]
lintran<-function(x,s1=c(0,1),s2=c(0,1)) {a=diff(s2)/diff(s1);b=s2[1]-a*s1[1];return(a*x+b)}
for(i in ec('magrittr,data.table,statnet,latentnet,BradleyTerry2')) library(i,character.only=T)
```

```{r orig}
o<-data.table(
  m=letters[1:15]
  ,s=rnorm(n = 15) %>% lintran(.,range(.),c(80,100)) %>% round() %>% sort()
)
o<-o[2:(nrow(o)-1)]
```

```{r edge,results='asis'}
e<-list()
for(i in 1:nrow(o)) for(j in setdiff(1:nrow(o),i)) {
  if(o[i,s]>=o[j,s]) e[[length(e)+1]]<-c(s=o[i,m],r=o[j,m])
}
e<-do.call(rbind,e) %>% data.table() %>% setorder()
head(e)
apply(e,1,function(x) cat(c(x[1],'\t',x[2],'\n'),sep=''))
```

```{r net}
n<-network(x = e,directed = T,matrix.type='edgelist')
(b<-as.matrix.network.adjacency(n))
(bc<-countsToBinomial(b))
```

```{r fitbtl}
f<-BTm(outcome = cbind(win1,win2)
     #  %>% jitter(.,.01) %>% abs() 
       ,player1,player2,data=bc)
f
```

```{r manual-cloglog}
f1<-glm.fit(y=f$model$Y[,1],x=f$model$X %>% jitter(amount = .001),family=binomial(link="cloglog"))
```

```{r}
library(glmnet)
f1<-glmnet(y=f$model$Y[,1],x=f$model$X,family=binomial(link="cloglog"))
```


```{r}
#https://github.com/jlaake/RMark/blob/master/RMark/R/inverse.link.R
inverse.link <-
function(x,link)
{
switch(link,
logit=1/(1+exp(-x)),
log=exp(x),
loglog=exp(-exp(-x)),
cloglog=1-exp(-exp(x)),
identity=x,
mlogit=1/(1+sum(exp(-x))),
sin=(sin(x)+1)/2,
Logit=1/(1+exp(-x)),
Log=exp(x),
LogLog=exp(-exp(-x)),
CLogLog=1-exp(-exp(x)),
Identity=x,
MLogit=1/(1+sum(exp(-x))),
Sin=(sin(x)+1)/2
)
}
p<-coef(f1) %>% inverse.link(link='cloglog')
p
plot(sort(p))
```

